### ISSUE TITLE
Cannot filter a map's key by a lvar

### ISSUE THREAD

**Issue by hongheng** [flybot-sg/lasagna-pull#68]
### Problem

Cannot filter a map's key by a lvar, which is used multiple times in the pattern. Currently, it's run like this:

```clojure
((pull/query '{:a {:a-id {:ref ?b-id}}
               :b {?b-id {:data ?data}}})
 {:a {:a-id {:ref :b-id}}
  :b {:b-id {:data 1}}})
=> {?b-id :b-id, &? {:a {:a-id {:ref :b-id}}, :b {}}}
```

### Suggestion
Support this feature.

**Comment by robertluo** [comment]
This feature currently is out of the scope.
